import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 390, height: 844 } })
const errs=[]; p.on('pageerror', e=>errs.push(e.message))
await p.goto('http://localhost:4173/#/login'); await p.getByRole('button', { name: /^Patient$/ }).click(); await p.waitForURL(/#\/app$/)
await p.goto('http://localhost:4173/#/assistant'); await p.waitForTimeout(800)
await p.getByRole('button', { name: /^Language/ }).first().click(); await p.getByRole('radio', { name: /Naijá/ }).click(); await p.waitForTimeout(400)
await p.screenshot({ path: 'qa/shots/ai-empty.png' })
await p.locator('#ai-input').fill('My brother no dey breathe well and im chest dey pain am'); await p.getByRole('button', { name: 'Send' }).click(); await p.waitForTimeout(1500)
await p.screenshot({ path: 'qa/shots/ai-answer.png' })
await p.getByRole('button', { name: /^Language/ }).first().click(); await p.getByRole('radio', { name: /Yorùbá/ }).click()
await p.goto('http://localhost:4173/#/emergency'); await p.waitForTimeout(800); await p.screenshot({ path: 'qa/shots/em-yo.png' })
const w=await p.evaluate(()=>[document.documentElement.scrollWidth, innerWidth]); console.log('width', w, 'errors', errs)
await b.close()
