import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, geolocation: { latitude: 6.45, longitude: 3.43 }, permissions: ['geolocation'] })
const p = await ctx.newPage()
const errs = []; p.on('pageerror', e => errs.push(e.message))
const U = 'http://localhost:4173/#'
await p.goto(U + '/'); await p.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
await p.goto(U + '/emergency'); await p.reload(); await p.waitForTimeout(1200)
await p.screenshot({ path: 'qa/shots/f-emergency.png' })
const nb = await p.$('[data-testid=nearest-emergency] button:has-text("Use my location")'); if (nb) { await nb.click(); await p.waitForTimeout(1000) }
await p.screenshot({ path: 'qa/shots/f-emergency-loc.png', fullPage: true })
console.log('call href', await p.getAttribute('[data-testid=call-nearest]', 'href'))
await p.goto(U + '/hospitals/h_lagooncrest'); await p.waitForTimeout(1200)
console.log('profile freshness', await p.getAttribute('[data-freshness]', 'data-freshness'))
await p.screenshot({ path: 'qa/shots/f-profile.png', fullPage: true })
await p.goto(U + '/find'); await p.waitForTimeout(1500)
console.log('card freshness', await p.$$eval('[data-freshness]', els => els.map(e => e.dataset.freshness).slice(0, 5)))
await p.screenshot({ path: 'qa/shots/f-find.png' })
await p.goto(U + '/login'); await p.waitForTimeout(600)
await p.getByRole('button', { name: /^Hospital$/ }).click(); await p.waitForURL(/#\/hospital$/)
await p.waitForTimeout(1800)
await p.screenshot({ path: 'qa/shots/f-dash.png' })
console.log('notif', await p.evaluate(() => JSON.parse(localStorage.getItem('medichub.db.v6')).notifications.filter(n => n.userId === 'u_lagooncrest' && n.type === 'system').map(n => n.title)))
await p.click('[data-testid=confirm-status]'); await p.waitForTimeout(800)
console.log('panel after confirm', await p.$('[data-testid=freshness-panel]') ? 'still' : 'gone')
await p.goto(U + '/hospital/status'); await p.waitForTimeout(1000)
await p.screenshot({ path: 'qa/shots/f-status.png', fullPage: true })
await p.goto(U + '/hospitals/h_lagooncrest'); await p.waitForTimeout(1000)
console.log('profile after', await p.getAttribute('[data-freshness]', 'data-freshness'))
const ow = await p.evaluate(() => document.documentElement.scrollWidth > innerWidth)
console.log('overflow', ow, 'errors', errs)
await b.close()
