// Clean phone screenshots for the app walkthrough video (demo build on :4173).
import { chromium } from 'playwright'
const BASE = 'http://localhost:4173/', OUT = process.env.OUT
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const ctx = await b.newContext({ viewport: { width: 430, height: 932 }, deviceScaleFactor: 2, timezoneId: 'Africa/Lagos' })
const p = await ctx.newPage()
const hideToasts = () => p.addStyleTag({ content: '[role=status].fixed, [data-sonner-toaster], .toast, [aria-live] > div { display:none !important }' }).catch(() => {})
await p.goto(BASE + '#/'); await p.waitForTimeout(1800); await p.screenshot({ path: `${OUT}/v-landing.png` })
await p.goto(BASE + '#/login'); await p.waitForTimeout(800)
await p.getByRole('button', { name: /Patient/ }).click(); await p.waitForURL(/#\/app/); await p.waitForTimeout(4500)
await p.goto(BASE + '#/hospitals/h_lagooncrest'); await p.waitForTimeout(1500)
await p.locator('#svc-h').evaluate((e) => window.scrollTo(0, e.getBoundingClientRect().top + scrollY - 90)); await p.waitForTimeout(500)
await p.screenshot({ path: `${OUT}/v-prices.png` })
await p.getByRole('button', { name: 'Book', exact: true }).nth(1).click(); await p.waitForTimeout(700)
await p.locator('[role=dialog] button:not([disabled])').filter({ hasText: /^(Today|Mon|Tue|Wed|Thu|Fri|Sat|Sun)/ }).nth(1).click(); await p.waitForTimeout(500)
await p.screenshot({ path: `${OUT}/v-times.png` })
await p.locator('[role=dialog] button:not([disabled])').filter({ hasText: /place/ }).first().click()
await p.getByRole('button', { name: 'Continue' }).click(); await p.waitForTimeout(500)
const opts = await p.locator('[data-testid=doctor-select] option').allInnerTexts()
await p.locator('[data-testid=doctor-select]').selectOption({ index: 1 })
await p.locator('[data-testid=doctor-select]').evaluate((e) => e.scrollIntoView({ block: 'center' })); await p.waitForTimeout(300)
await p.screenshot({ path: `${OUT}/v-doctor.png` })
await p.getByTestId('pay-and-book').scrollIntoViewIfNeeded(); await p.waitForTimeout(300)
await p.screenshot({ path: `${OUT}/v-paybtn.png` })
await p.getByTestId('pay-and-book').click(); await p.waitForURL(/pay\/test/); await p.waitForTimeout(900)
await p.screenshot({ path: `${OUT}/v-checkout.png` })
await p.getByTestId('test-pay').click(); await p.waitForURL(/payment\/verify|app\/bookings/, { timeout: 15000 }); await p.waitForTimeout(2600)
await p.screenshot({ path: `${OUT}/v-paid.png` })
const link = p.getByRole('link', { name: /booking pass/i }); if (await link.count()) { await link.first().click(); await p.waitForTimeout(1500); await p.screenshot({ path: `${OUT}/v-pass.png` }) }
await p.goto(BASE + '#/find'); await p.waitForTimeout(2000); await p.screenshot({ path: `${OUT}/v-find.png` })
await p.goto(BASE + '#/emergency'); await p.waitForTimeout(2000); await p.screenshot({ path: `${OUT}/v-emergency.png` })
// doctor
await p.evaluate(() => { for (const k of Object.keys(localStorage)) if (/session|token/i.test(k)) localStorage.removeItem(k) })
await p.goto(BASE + '#/login'); await p.waitForTimeout(800)
await p.getByRole('button', { name: /Doctor/ }).click(); await p.waitForURL(/#\/doctor/); await p.waitForTimeout(4500)
await p.screenshot({ path: `${OUT}/v-doctordash.png` })
// hospital live status
await p.evaluate(() => { for (const k of Object.keys(localStorage)) if (/session|token/i.test(k)) localStorage.removeItem(k) })
await p.goto(BASE + '#/login'); await p.waitForTimeout(800)
await p.getByRole('button', { name: /Hospital/ }).click(); await p.waitForURL(/#\/hospital/); await p.waitForTimeout(4500)
await p.goto(BASE + '#/hospital/status'); await p.waitForTimeout(1500); await p.screenshot({ path: `${OUT}/v-status.png` })
await p.mouse.wheel(0, 700); await p.waitForTimeout(600); await p.screenshot({ path: `${OUT}/v-status2.png` })
await p.goto(BASE + '#/hospital/bookings'); await p.waitForTimeout(1500); await p.screenshot({ path: `${OUT}/v-hbookings.png` })
console.log('doctor options', opts)
await b.close()
